from django.test import TestCase
from django.core.exceptions import ValidationError
from user_app.models import User
import re

class user_test(TestCase):
    pass